# Ejercicio día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [15]:
import numpy as np


In [ ]:
a=np.zeros([16]) #se crea una matriz con 16 elementos =0 proveniente de una de 4*4
b=np.arange(16) # se crea una amtriz de 16 elementos proveniente de una 4*4
c=np.random.choice(b,int(16/2),replace=False) # se elige al azar de una matriz rango b con tamaño 8 , se coloca el replace para que no se puedan agarrar dos veces aleatoriamente el mismo valor
a[c]=1 # se asigna 1 a los valores de la matriz c en a tomados al azar
a.resize(4,4) # se vuelve a convertir en matriz
a

In [ ]:
c

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [ ]:
e=np.zeros([5,2])
r=np.ones([5,2])
e



In [ ]:
r

In [ ]:
#INCISO 1
e.reshape((10,1)) # se transforman en vectores columna reordenando la matriz a una columna y varias filas
r.reshape((10,1))


In [ ]:
#Inciso 2
np.dstack((e[:, np.newaxis], r[:, np.newaxis])) # se apilan sobre una nueva dimension en e y r

In [ ]:
#INCISO 3

np.vstack((e.reshape(1,10),r.reshape(1,10))) # se apilan de forma vertical los vectores fila

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [ ]:
x=np.random.random((3,1))
y=np.random.random((3,1))
z=np.random.random((3,1))
def funcion(x,y,z):
    return(2*x+3*y+z**2)


In [ ]:
funcion(x,y,z)

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [ ]:
y=np.random.randint(0,2,(50,50)) 
#area a encontrar = area conocida*elementos dentro/elementos totales
p=np.count_nonzero(y==1) #total de elementos que tienen 1 en la matriz
area_grande=50*50
p

In [ ]:
x=y[15:35,15:35] # se delimita la porcion de 20 centimetros del cuadrado
x

In [ ]:
b=x>0
b

In [ ]:
t=x[b]
t
area_pequeña=((np.count_nonzero(t==1)*area_grande))/p #se aproxima el area con la proporcion de areas y cantidad de unos en ambos cuadrados
area_pequeña

In [ ]:
np.count_nonzero(t==1)

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [ ]:
#ARRAY CREATION ROUTINES
np.identity(2) # devuelve una matriz identidad de n elementos

In [ ]:
np.eye(3) # devuelve una matriz de dimensiones n de 2dimensiones con uno en las diagonales y zeros en lo demas

In [ ]:
np.ones((3,3),dtype=int) # devuelve un arreglo de 1 con las dimensiones especificadas  y los tipos especificados

In [ ]:
np.zeros((5,5),dtype=int) # devuelve una matriz de ceros con las dimensiones y tipos especificados

In [ ]:
x=np.arange(6)
np.zeros_like(x) # devuelve una matriz de ceros identica a una que especifiquemos

In [ ]:
np.full((5,5),"hola") # regresa una matriz de dimension especificada con un valor dado

In [ ]:
r=np.array([1,2,3])
r
np.full_like(r,(1)) #devuelve un arreglo con un valor dado en la misma forma que una especificada

In [ ]:
np.array([[1,2],[2,3]]) #crea un arreglo 

In [ ]:
np.asarray("holas") #convertir lo ingresado como arreglo

In [ ]:
x=np.asmatrix([[1,2,3,4],[3,7,8,9]])
x[0,1]        #convertir el input como una matriz
    

In [ ]:
np.copy(x) #devuelve una copia del  arreglo especificado

In [ ]:

np.fromstring('1,2',dtype=int,sep=',')# una nuevo arreglo proveniente de un string

In [ ]:
x=np.array([1,2,3,4])
y=np.array(['a','bn','e','y'])
z=np.array([1.3,4,5,6])
l=np.core.records.fromarrays([x,y,z],names='a,b,c')
print(l)
type(l) # crea un tipo de arreglo de varios objetos , debe ser las misma dimension

In [ ]:
t=np.core.records.fromrecords([('hola','adios'),('jorge','juan')],names='a1,a2')
t.a1
t.a2 #crea un tipo de arreglo con los objetos especificados

In [ ]:
np.arange(1,5) # devuelve valores espaciados de la misma manera en un intervalo

In [ ]:
np.linspace(0,20,5) # devuelve numeros dentro de un rango con espaciamiento identico entre ellos

In [ ]:
np.logspace(1,100,10) # regresa numeros con espaciamiento identico aplicado a logarimos

In [ ]:
np.geomspace(1,100,10) # devuelve una progresion geometrica

In [ ]:
 nx, ny = (3, 2)
 x = np.linspace(0, 1, nx)
 y = np.linspace(0, 1, ny)
 xv, yv = np.meshgrid(x, y) # devuelve una matriz de coordenadas apartir de un vector
 xv


In [ ]:
x=np.arange(9).reshape((3,3))
x
np.diag(x) # regresa la diagonal de una matriz especificando un valor k que va desde -1 hasta el rango de la matriz

In [ ]:
x=np.arange(10).reshape(5,2)
np.diagflat(x,k=4) # regresa una diagonal especificando su posicion con k y regresa el rango en la diagonal

In [ ]:
x=np.arange(10).reshape(5,2)

np.tri(5,5,k=1) # crea una matriz con unos en y bajo la diagonal segun la posicion k especificada y devuelve ceros sobre ella

In [ ]:
x=np.arange(10)
np.tril(x,k=2) # devuelve una diagonal con el rango del arreglo especificado en la posicion especificada el triangulo inferior

In [ ]:
x=np.arange(10)
np.triu(x,k=4) # devuelve la parte superior del triangulo en la matriz en la posicion especificada

In [ ]:
x=np.arange(10)
np.vander(x) # devuelve una matriz de vander , los ordena y los suma

In [ ]:
x=np.arange(10)
np.mat(x) # interpreta el output como una matriz
x[3]
x

In [ ]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
np.bmat([[A], [B]]) #crea una matriz a partir de un bloque de strings

In [ ]:
r=np.array(9)
y=r
h=np.copyto(r,t)
# copia los valores de un arreglo a otro

In [ ]:
r=np.array(9)
np.shape(r) #regresa la forma de un arreglo

In [ ]:
r=np.arange(9)
r.reshape(3,3) # cambia la estructura de un arreglo sin modificar sus datos

In [ ]:
r=np.array([[1,2,3,4],[4,5,6,7]])
np.ravel(r,order='c')
#r.flatten() # devueve un arreglo tipo flattended continuo

In [ ]:
r=np.arange(9)

l=np.moveaxis(r,0,-1)
l#mueve los ejes de un un arreglo a otra posicion indicada dejando todo los demas igual

In [ ]:
t=np.array([[1,2,3],[4,5,6]]) # transpone los elementows de un arreglo

In [ ]:
np.transpose(t)

In [ ]:
np.atleast_1d(t) # Convierte el input a un arreglo de almenos una dimension

In [ ]:
np.atleast_2d(t) # Convierte el input a un arreglo de almenos dos dimension

In [ ]:
np.atleast_3d(t) # convierte input en 3 dimensiones

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1],[4]]) # broadcasting suma dos vectores
x+y 

In [ ]:
x=np.array([1,2,3])
np.broadcast_to(x,(5,3)) # coloca un arreglo en una nueva forma

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y) # hace el broadcast de cualquier numero de arreglos

In [ ]:
x = np.array([[1,2,3,4,5]])
np.expand_dims(x,2) #expande la forma de cualquier arreglo

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.concatenate((a, b), axis=0)
# concatena una secuencia de arreglos alrededor de un eje

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.stack((a,b),axis=1) # une una secuencia de arreglos alrededor de un eje

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.column_stack((a,b)) # pone arreglos 1d en arreglos de columnas 2d

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.dstack((a,b)) #pone los arreglos en orden  a lo largo del tercer eje

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.hstack((a,b))

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.vstack((a,b)) # pone la secuencia verticalmente

In [ ]:
np.block([[1,2],[3,4]]) # convierte un bloque en un arreglo

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.split(a,2) # divide un arreglo en diferentes numeros especificados

In [ ]:
x=np.arange(8)
np.array_split(x,3) # divide un arreglo dentro de una cantidad especificadas

In [ ]:
x=np.arange(8).reshape(4,2)
np.hsplit(x,2) 

In [ ]:
x=np.arange(8).reshape(4,2)
np.vsplit(x,2) 

In [ ]:
A=("hola")
np.tile(A,4) # repite el numero de veces indicado un objeto y lo vuelve un arreglo

In [ ]:

np.repeat(3,4) # repite un elemento el numero de veces indicados
         

In [ ]:
L = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
L
np.delete(L,1,0) # borra el elemento de un arreglo de un indice especificado 0 para fila y 1 para columna

In [ ]:
L = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.insert(L,1,4,axis=0)  # inserta los argumentos alrededor del eje especificado

In [ ]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)
# crea un arreglo en el eje especificado de varios objetos

In [ ]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,5)) #regresa un nuevo arreglo con la forma especificada

In [ ]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a,'fb') # elimina los ceros de un arreglo


In [ ]:
r=np.array([[1,4,5,6],[4,7,8,9,0]])
np.unique(r) # devuelve los valores unicos de un arreglo

In [ ]:
r=np.array([[1,4,5,6],[4,7,8,9,0]])
np.flip(r) #en el eje especificado se voltean los elementos del arreglo

In [ ]:
A=np.arange(10).reshape(5,2)
np.fliplr(A) # Reverse de izquierda a derecha del arreglo

In [ ]:
A=np.arange(10).reshape(5,2)
np.flipud(A) # Reverse del arreglo de arriba hacia abajo

In [ ]:
A=np.arange(10).reshape(5,2)
A # Reshape cambia el arreglo a la forma especificada

In [ ]:
x = np.arange(10)
np.roll(x, 2)
# el arreglo se cambiado desde las posiciones que se indican y se ponen al inicio

In [ ]:
 m = np.array([[1,2],[3,4]], int)
np.rot90(m)
#rota 90 grados el arreglo

In [ ]:
np.binary_repr(8) #devuelve la representacion binaria de un numero

In [ ]:
np.base_repr(5) # retorna un string representando el numero dado en la base del sistema

In [ ]:
 x = np.invert(np.array(13, dtype=np.uint8))




In [ ]:
 np.left_shift(5, 2)


In [ ]:

np.left_shift(5, 2)


In [ ]:
x1="hola"
x2="mundo"
np.char.add(x1,x2) #concatena una cadena de texto


In [ ]:
np.char.multiply(x1,5) # devuelve n veces la cadena de texto especificada

In [ ]:
np.char.capitalize(x1) # convierte en mayuscula la primera letra 

In [ ]:
np.char.lower(x1) # cambia todas las letras a minusculas

## INCISO 2

In [ ]:

x = np.random.random((10,10))
y = np.arange(1,10,2)

np.savez('Doc.bin', objA = x, objB = y)

In [ ]:
p = np.load('Doc.bin.npz')

In [ ]:
p['objA']

In [ ]:
p['objB']

## INCISO 3

In [ ]:

x = np.random.random((10,10))
y = np.arange(1,10,2)

np.savetxt('Doc.out',b,delimiter=',')

In [ ]:
np.loadtxt('Doc.out',delimiter=',')

## INCISO 4

In [43]:
def estimacionMCO():
    import csv
    import numpy as np
    data=np.loadtxt('mco_prueba.csv',delimiter=',',skiprows=1)
    return(data)

In [44]:
r=estimacionMCO()
r    
    
        
        

array([[30., 92., 19., 20., 95., 23., 58.],
       [60., 29., 39., 81., 59., 52., 80.],
       [10., 26., 81., 66., 37., 98., 37.],
       [82., 19., 16.,  7., 78., 35.,  0.],
       [99., 58., 53., 80., 45., 80., 89.],
       [37., 70., 86.,  6.,  5., 75., 64.],
       [ 0., 63., 43., 42., 11., 65., 35.],
       [43., 82., 94.,  7., 39., 92., 94.],
       [53., 47., 31., 31., 51.,  6., 80.],
       [75., 33., 15., 71., 13., 50., 93.],
       [33., 74.,  6., 19., 46., 97., 79.],
       [35., 24., 44., 88., 73., 45., 32.],
       [25.,  6., 56., 39., 19., 86., 87.],
       [29., 96., 71., 32., 49.,  4., 72.],
       [35., 56., 57., 94., 68., 85.,  2.],
       [22., 95.,  2., 83., 10.,  0., 23.],
       [85.,  6., 74., 74., 52., 87., 63.],
       [86., 46., 70., 50., 49., 48., 41.],
       [37., 59., 52.,  4., 92., 38., 62.],
       [92., 98., 97., 58., 53., 59., 29.],
       [47.,  3., 63., 53., 30., 64., 58.],
       [89., 29., 52.,  1., 45., 54.,  6.],
       [81., 53., 48., 28., 34.,

In [45]:
matrizx=r[:,0:6] #xtx todo inverso *xtransp *y
matrizx
matrizy=r[:,6:7]

In [46]:
matrizy

array([[58.],
       [80.],
       [37.],
       [ 0.],
       [89.],
       [64.],
       [35.],
       [94.],
       [80.],
       [93.],
       [79.],
       [32.],
       [87.],
       [72.],
       [ 2.],
       [23.],
       [63.],
       [41.],
       [62.],
       [29.],
       [58.],
       [ 6.],
       [16.],
       [41.],
       [ 7.],
       [14.],
       [88.],
       [61.],
       [29.],
       [66.],
       [10.],
       [99.],
       [39.]])

In [47]:
A=matrizx.T@matrizx
B=np.linalg.inv(A)
C=matrizx.T@matrizy
MatrizBeta=B@C
MatrizBeta

array([[-0.06441992],
       [ 0.2372137 ],
       [ 0.18383896],
       [ 0.0734313 ],
       [ 0.21289056],
       [ 0.34480412]])